name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us fix it.

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Edge
        - Brave
        - Arc
        - Other Chromium-based browser
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: "You can find this in browser settings or by visiting chrome://version"
      placeholder: "e.g., 120.0.6099.109"
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: "Find this in chrome://extensions (enable Developer mode)"
      placeholder: "e.g., 0.12.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem (drag & drop images here)

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: |
        Open DevTools (F12) → Console tab, and paste any error messages here.
        For background script errors: chrome://extensions → CleanClip → "Inspect views: service worker"
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
